### ISSUE TITLE
TODO: First Release

### ISSUE THREAD

**Issue by alex9smith** [alex9smith/ascendant#1]
**DB**
- [ ] SQL to create empty tables

**Replay parsing**
- [ ] Test that requests can always handle long replays
- [ ] Finish parser methods in `celery-worker/replay_summary.py`
- [ ] Add DB insert code to `celery-worker/db_client.py`

**Adding matches**
- [ ] Check that the match hasn't already been uploaded

**Stats**
- [ ] Add methods in `/app/api.py` to retrieve stats from the DB

**Website**
- [ ] Create management page to add / remove leagues & teams
- [ ] League summary on homepage
- [ ] Team view template
- [ ] Hero view template
- [ ] Player view template
- [ ] Match view template

**Documentation**
- [ ] Add docstrings to all code  
- [ ] Update readme
